version: '3'

services:
  ssl-api:
    container_name: ssl-api
    image: dv4all/ssl-api-express:0.0.3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: "0.0.0.0."
      PORT: "8433"
    ports:
      - "8433:8433"
    networks:
      - net

networks:
  net:
