version: '3'

services:
  ssl-api:
    container_name: ssl-api
    image: dv4all/ssl-api-fastify:0.0.3
    build:
      context: .
      dockerfile: Dockerfile_v14
    environment:
      HOST: "0.0.0.0."
      PORT: "8434"
    ports:
      - "8434:8434"
    networks:
      - net

networks:
  net: